// Generated by CoffeeScript 1.4.0
/*
	(c) 2012 - Juanma Orta - Coffeescript version
	app.coffee
	+ social.coffee
    + maps.coffee
    + forms.coffee
	DO NOT edit the .js file
*/

/*global $:false, define:false, require:false, requirejs:false, console:false
*/

requirejs.config({
  paths: {
    'jquery': 'lib/jquery-1.8.3.min'
  }
});

require(['jquery', 'timer', 'util'], function(jquery, timer, util) {
  $("input.timedisplay").blur(function(e) {
    return $(this).val(util.zerofill($(this).val()));
  });
  $(".timer_start").click(function(e) {
    var lapse, lapses, m_field, s_field, timer_field, _i, _len, _minutes, _seconds, _time;
    e.preventDefault();
    timer_field = $(this).attr("data-rel");
    lapses = $("input[data-rel=" + timer_field + "]");
    for (_i = 0, _len = lapses.length; _i < _len; _i++) {
      lapse = lapses[_i];
      _time = parseInt($(lapse).val(), 10);
      if ($(lapse).attr("name") === "minutes") {
        _minutes = _time;
        m_field = lapse;
      } else if ($(lapse).attr("name") === "seconds") {
        _seconds = _time;
        s_field = lapse;
      }
    }
    if (timer.count(_minutes, _seconds, "down", m_field, s_field)) {
      return $(this).html("Pause <i class=\"icon-pause icon-white\"></i>").removeClass("btn-success").addClass("btn-danger");
    }
  });
  return false;
});
