// Generated by CoffeeScript 1.4.0
/*
Timer
timer.coffee
(c) 2012 - Juanma Orta - Coffeescript version
DO NOT edit the .js file
*/

/*global $:false, console:false, define:false, alert:false
*/

define(['jquery', 'date', 'util'], function(jquery, date, util) {
  var _countdown, _counter, _date, _mins_field, _ref_date, _secs_field;
  _counter = null;
  _date = null;
  _ref_date = null;
  _secs_field = null;
  _mins_field = null;
  _countdown = function() {
    _date.addSeconds(-1);
    $(_mins_field).val(util.zerofill(_date.getMinutes()));
    $(_secs_field).val(util.zerofill(_date.getSeconds()));
    if (_date.getSeconds() === 0 && _date.getMinutes() === 0) {
      clearInterval(_counter);
    }
  };
  return {
    count: function(minutes, seconds, direction, mins_field, secs_field) {
      if (minutes > 0 || seconds > 0) {
        _mins_field = mins_field;
        _secs_field = secs_field;
        if (Date.validateMinute(minutes) && Date.validateSecond(seconds)) {
          _date = Date.today().set({
            minute: minutes,
            second: seconds
          });
          _ref_date = Date.today().set({
            minute: 0,
            second: 0
          });
          _counter = setInterval(_countdown, 1000);
          return true;
        } else {
          console.log("seconds or minutes not valid");
          return false;
        }
      } else {
        return false;
      }
    }
  };
});
